Update get_http_test to fail only when we expect it to
Before Change
```
~>  go test ./...
--- FAIL: TestHttpGetter__XTerraformGetConfiguredGettersBypass (0.01s)
    --- FAIL: TestHttpGetter__XTerraformGetConfiguredGettersBypass/configured_getter_for_git_protocol_switch (0.00s)
        get_http_test.go:742: http://127.0.0.1:52744/start
        get_http_test.go:726: making request
        get_http_test.go:903: serving start
        get_http_test.go:756: expected download not supported for scheme, got: /usr/local/bin/git exited with -1:
    --- FAIL: TestHttpGetter__XTerraformGetConfiguredGettersBypass/configured_getter_for_multiple_protocol_switch (0.00s)
        get_http_test.go:742: http://127.0.0.1:52746/start
        get_http_test.go:726: making request
        get_http_test.go:903: serving start
        get_http_test.go:756: expected download not supported for scheme, got: /usr/local/bin/git exited with -1:
FAIL
```

After Change
```
~>  go test ./...
ok      github.com/hashicorp/go-getter/v2       13.908s
?       github.com/hashicorp/go-getter/v2/helper/testing        [no test files]
ok      github.com/hashicorp/go-getter/v2/helper/url    (cached)

```